- name: Deploy TFM client
  hosts: all # we want the client also in the server, for netcdf4 local testing
  vars:
    user: "{{ ansible_user }}"
    jupyterhub_domain: 193.146.75.211
    jupyterhub_data: "{{ ansible_env.HOME }}/data"
    jupyterhub_httpd_proxy: True
    jupyterhub_docker_image: zequihg50/tfm
  vars_files:
    - authenticator-{{ inventory_hostname }}.yml
  tags: jupyterhub
  roles:
    - jupyterhub
  pre_tasks:
    - name: Add hostname to /etc/hosts
      become: True
      lineinfile:
        path: /etc/hosts
        line: 127.0.0.1 {{ ansible_hostname }}
  tasks:
    - name: Add conda to user bashrc
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: >-
          . {{ miniconda_prefix }}/etc/profile.d/conda.sh

    - name: Copy user whitelist
      copy: src=tfm.whitelist dest={{ jupyterhub_runtime }}/whitelist

    - name: Template httpd conf
      become: True
      template: src={{ playbook_dir }}/jupyterhub.conf.j2 dest=/etc/apache2/sites-available/jupyterhub.conf
      notify:
        - restart httpd

    - name: Restart jupyterhub
      become: True
      service: name=jupyterhub state=restarted
  handlers:
    - name: restart httpd
      become: True
      service: name=apache2 state=restarted

- name: Deploy TFM server
  hosts: tfm-servidor
  vars:
    root: "{{ ansible_env.HOME }}/tds"
    ansible_python_interpreter: /usr/bin/python3 # required if using apt packages
    jdk_root: "{{ ansible_env.HOME }}/jdk"
    tomcat_home: "{{ root }}"
    tomcat_base: "{{ ansible_env.HOME }}"
    tds_content_root_path: "{{ tomcat_home }}/content"
    tds_root_catalog: catalog.xml
  tags: tds
  roles:
    - role: jdk-source
    - role: tomcat-source
    - role: tomcat
      # These are role defaults, they are showed here for illustration
      # You can tune these paremeters to suit your needs
      tomcat_name: tds
      tomcat_webapps: [tds]
      tomcat_http_port: 8080
      tomcat_shutdown_port: 8005
      tomcat_Xmx: 2048m
      tomcat_Xms: 512m
      tds_version: 5.0.0-beta6
      tds_content_root_path: "{{ root }}"
      tds_context: thredds
  tasks:
    - import_tasks: ansible-thredds-cluster/utils/tomcat-service.yml
      vars:
        tomcats: [tds]
      environment:
        JAVA_HOME: "{{ jdk_root }}"

    - name: Clean
      file: path={{ root }} state=absent
      tags: [never, purge, clean]

    - name: Purge
      file: path={{ downloads }} state=absent
      tags: [never, purge]

- name: Deploy HSDS
  hosts: tfm-servidor
  vars_files:
    - secrets.yml
  tags: hsds
  roles:
    - role: hsds
  
  
